### ISSUE TITLE
ZPOOL_NUM_PROPS 26 not 23

### ISSUE THREAD

**Issue by WinndyBoy** [akatrevorjay/pyzfscore#6]
I'm getting the following error 

cffi.ffiplatform.VerificationError: enum zpool_prop_t: ZPOOL_NUM_PROPS has the real value 26, not 23

I'm assuming I have wrong version of librarys or pools ? But can't find anything on this to understand any better. I'm using ArchLinux with latest zfs 0.6.3_r170_gd958324f_3.18.5_1-1

**Comment by akatrevorjay** [comment]
Yeah, this means the enums are not equal to what your system has. Sorry, I haven't been keeping up on this in quite some time (I haven't personally used this for over a year in projects.).

You can copy that portion of the enums out of your headers for libzfs into the appropriate CFFI include methods.

**Comment by DatanoiseTV** [comment]
This is fixed in my repository. Check out my pull request.

**Comment by akatrevorjay** [comment]
Thanks @DatanoiseTV
